name: chatty
description: a simple chat application

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # di
  get_it: ^7.2.0

  # state management
  flutter_bloc: ^8.0.0

  # i18n
  intl: ^0.17.0

  # data/network
  freezed_annotation: ^1.0.0
  dio: ^4.0.4
  retrofit: ^3.0.0
  json_annotation: ^4.3.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

  # local storage
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.13

  # ui
  flutter_svg: ^1.0.3

  logger: ^1.1.0
  collection: ^1.15.0
  image_picker: ^0.8.4+9
  permission_handler: ^9.2.0
  synchronized: ^3.0.0
  uuid: ^3.0.6
  image_size_getter: ^1.0.0

  common_widgets:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_widgets
  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models
  common_network_components:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_network_components
  common_utilities:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_utilities
  timeago:
    git:
      url: https://github.com/kume1a/timeago.dart.git
      path: timeago
  static_i18n:
    git:
      url: https://github.com/kume1a/flutter_static_i18n.git
  global_navigator:
    git:
      url: https://github.com/kume1a/flutter_global_navigator.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.7.2

  flutter_native_splash: ^2.0.4
  flutter_launcher_icons: ^0.9.2

  build_runner: ^2.1.5
  retrofit_generator: ^4.0.1
  injectable_generator: ^1.5.3

  freezed: ^1.1.1
  injectable: ^1.5.0
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffffff"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

  #  color_dark: "#042a49"
  #  image_dark: assets/images/logo_550_dark.png

  fullscreen: true
